name: "jadelr's notebook"
favicon: null
layout_spectrum: 0.8619640239048749
typography_spectrum: 0.5699364973697811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5900430828332901
  lightness: 0.9984720940701663
  saturation: 0.0033105816692113876
  rhythmicContrast: 0.5043491909746081
purpose: []
